### ISSUE TITLE
Errrr.... How Could I Find IP Address Of the New Coming Connection?

### ISSUE THREAD

**Issue by GrassLake** [aquamoth/SocketMessaging#2]
I'm a C# newbie, and a lot of things I didn't know...
Thanks For Your Great Work at first. It's a very easy Use Tool. I could bulid my network at minimum code cost.
Although I could check connection pool the Tool offered to Identified Which Connection is new comer... I think is a too-complexed method.
Have read your guideline, I didn't find any thing about how to get the IP Address of new Connection.
Could you solve the little problem， please？
Thanks again.

**Comment by aquamoth** [comment]
I suggest you extract the underlying socket and read the endpoints for there.
Example:
`
    var socket = e.Connection.Socket;
    var localIPEndPoint = socket.LocalEndPoint as System.Net.IPEndPoint;
    var remoteIPEndPoint = socket.RemoteEndPoint as System.Net.IPEndPoint;
    System.Diagnostics.Debug.WriteLine($"Local Endpoint: {localIPEndPoint.Address }:{localIPEndPoint.Port}");
    System.Diagnostics.Debug.WriteLine($"Remote Endpoint: {remoteIPEndPoint.Address }:{remoteIPEndPoint.Port}");
`

**Comment by GrassLake** [comment]
Yeah, It's so kind of you. 
The answer is detailed, and I already know this before...
OK, my original issue is "is there a method or event to Trigger When A New Connection is Coming In"...
It's my fault, and I have write a method to Pick Up new connection after it connected.
Thanks you anyway. Wish you a Sunny Day!
~~~
My Town is in far North; 
The weather = very Snowy;
Temperature = so cold... ;

: )

**Comment by aquamoth** [comment]
> OK, my original issue is "is there a method or event to Trigger When A New Connection is Coming In"...

Is it this you are seeking in the component?

    class Program
    {
        static SocketMessaging.Server.TcpServer _tcpServer;

        static void Main(string[] args)
        {
            _tcpServer = new SocketMessaging.Server.TcpServer();
            _tcpServer.Connected += TcpServer_Connected;
            _tcpServer.Start(8778);
            Console.ReadLine();
        }

        private static void TcpServer_Connected(object sender, ConnectionEventArgs e)
        {
            var socket = e.Connection.Socket;
            //...more code here...
        }
    }

I have a branch with sample code that never got merged. I'm doing that now. Take a look at it in case it helps you.

**Comment by GrassLake** [comment]
Yes, It's!
Emmm... Amazing!
`_tcpServer.Connected += TcpServer_Connected;`
And...
`_tcpServer.Connected += (s, e) => e.Connection.ReceivedRaw += Connection_ReceivedRaw;`
Could Be Used Together!
Now I can Sense new comer and Analyse the Client Info in two different event.
Thanks a lot, and I really need to keep an eye on LOVELY SocketMessaging to see if someday I could do  
a little work for it...
