### ISSUE TITLE
.net core support?

### ISSUE THREAD

**Issue by michael-dots** [aquamoth/SocketMessaging#3]
Any plans to update library and remove .net framework dependencies? Getting some warnings about it.

**Comment by aquamoth** [comment]
Sounds like a good idea.
Any PR is welcome; otherwise I'll look into it when I get a bit of time.

**Comment by aquamoth** [comment]
.Net Core is supported in [release 1.2.1](https://github.com/aquamoth/SocketMessaging/releases/tag/v1.2.1)
