### ISSUE TITLE
SendAsync

### ISSUE THREAD

**Issue by devhl-labs** [aquamoth/SocketMessaging#4]
Can you add a SendAsync method that returns a reply?  I'd like to send a message to another program and require a reply from that program.

**Comment by aquamoth** [comment]
How do you mean this would work? 

Multiple messages can be sent over one socket at once and there is no way to ensure which reply goes with what request, on the message layer. 

I think this needs to be handled on a higher protocol level, or by opening multiple connections.

**Comment by devhl-labs** [comment]
Another library that isn't being updated anymore has this feature.  They handle it by including the original message in the reply.

**Comment by aquamoth** [comment]
If you give me a link to that library or a similar implementation, I can consider it. 
Or better yet, write a PR.

One way to implement this could be to wrap a multiplexer around the socket, that handles message id's and message splitting. What do you think of that approach?

**Comment by devhl-labs** [comment]
The library is SimplSocket.  It hasn't been updated in a while, and it does not have async methods.  It uses multiplexer to accomplish it.  The SendReceive method accepts a byte[] to be sent and returns a byte[] that is the response.  I don't have an opinion on how it should be done, it's a bit beyond my knowledge.  

https://github.com/haneytron/simplsockets/blob/37361376e275eb1177401671898ab0d0751a5100/SimplSockets/SimplSocketClient.cs
